var translations = {
	"en": {
		"profile": "Profile",
		"freeWOD": "Free WOD",
		"training": "Training",
		"travelWOD": "Travel WOD",
		"calendar": "Calendar",
		"configuration": "Configuration",
		"language": "Language",
		"unitOfMeasurement": "Unit of measurement",
		"helpsActivate": "Helps activate",
		"warning": "WARNING",
		"responsibilities": "AppWod is not responsible for any damage caused. Consult a trainer and make suitable medical exams before using the application.",
		"spanish": "Spanish",
		"english": "English",
		"german": "German",
		"french": "French",
	    "italian": "Italian",
	    "portuguese": "Portuguese",
	    "user": "user",
	    "name": "Name",
	    "lastname": "Last name",
	    "country": "Country",
	    "showStadistics": "Show stadistics",
	    "contacts": "Contacts",
	    "nameAndSurname": "Name Surname",
	    "friends": "Friends",
	    "monday": "Monday",
	    "tuesday": "Tuesday",
	    "wednesday": "Wednesday",
	    "thursday": "Thursday",
	    "friday": "Friday",
	    "saturday": "Saturday",
	    "sunday": "Sunday",
	    "argentina": "Argentina",
	    "usa": "United States",
	    "crossfitterBeginner": "Crossfitter Beginner &nbsp; Level",
        "crossfitterIntermediate": "Crossfitter Intermediate &nbsp; Level",
        "crossfitterAdvanced": "Crossfitter Advanced &nbsp; Level",
        "crossfitterPro": "Crossfitter Pro &nbsp; Level",
        "club": "Club",
        "today": "Today"
	},
	"es": {
		"profile": "Perfil",
		"freeWOD": "WOD Libre",
		"training": "Entrenamiento",
		"travelWOD": "WOD de viaje",
		"calendar": "Calendario",
		"configuration": "Configuración",
		"language": "Idioma",
		"unitOfMeasurement": "Unidad de medida",
		"helpsActivate": "Activar ayuda",
		"warning": "ADVERTENCIA",
		"responsibilities": "AppWod no se hace responsable ante cualquier lesión ocasionada. Consulte a un entrenador y realice exámenes de apta médico antes de usar la aplicación.",
		"spanish": "Español",
		"english": "Inglés",
		"german": "Alemán",
		"french": "Frances",
	    "italian": "Italiano",
	    "portuguese": "Portugues",
	    "user": "usuario",
	    "name": "Nombre",
	    "lastname": "Apellido",
	    "country": "País",
	    "showStadistics": "Ver estadísticas",
	    "contacts": "Contactos",
	    "nameAndSurname": "Nombre Apellido",
		"friends": "Amigos",
		"monday": "Lunes",
	    "tuesday": "Martes",
	    "wednesday": "Miércoles",
	    "thursday": "Jueves",
	    "friday": "Viernes",
	    "saturday": "Sábado",
	    "sunday": "Domingo",
	    "argentina": "Argentina",
	    "usa": "Estados Unidos",
	    "crossfitterBeginner": "Crossfitter Nivel &nbsp; Principiante",
        "crossfitterIntermediate": "Crossfitter Nivel &nbsp; Intermedio",
        "crossfitterAdvanced": "Crossfitter Nivel &nbsp; Avanzado",
        "crossfitterPro": "Crossfitter Nivel &nbsp; Pro",
        "club": "Club",
        "today": "Hoy"
	}
}