var translations = {
	"en": {
		"profile": "Profile",
		"freeWOD": "Free WOD",
		"training": "Training",
		"travelWOD": "Travel WOD",
		"calendar": "Calendar",
		"configuration": "Configuration",
		"language": "Language",
		"unitOfMeasurement": "Unit of measurement",
		"helpsActivate": "Helps activate",
		"warning": "WARNING",
		"responsibilities": "AppWod is not responsible for any damage caused. Consult a trainer and make suitable medical exams before using the application",
		"spanish": "Spanish",
		"english": "English",
		"german": "German",
		"french": "French",
	    "italian": "Italian",
	    "portuguese": "Portuguese",
	    "user": "user",
	    "name": "Name",
	    "country": "Country",
	    "showStadistics": "Show stadistics",
	    "contacts": "Contacts",
	    "nameAndSurname": "Name Surname",
	    "friends": "Friends"
	},
	"es": {
		"profile": "Perfil",
		"freeWOD": "WOD Libre",
		"training": "Entrenamiento",
		"travelWOD": "WOD de viaje",
		"calendar": "Calendario",
		"configuration": "Configuración",
		"language": "Idioma",
		"unitOfMeasurement": "Unidad de medida",
		"helpsActivate": "Activar ayuda",
		"warning": "ADVERTENCIA",
		"responsibilities": "AppWod no se hace responsable ante cualquier lesión ocasionada. Consulte a un entrenador y realice exámenes de apta médico antes de usar la aplicación",
		"spanish": "Español",
		"english": "Inglés",
		"german": "Alemán",
		"french": "Frances",
	    "italian": "Italiano",
	    "portuguese": "Portugues",
	    "user": "usuario",
	    "name": "Nombre",
	    "country": "País",
	    "showStadistics": "Ver estadísticas",
	    "contacts": "Contactos",
	    "nameAndSurname": "Nombre Apellido",
		"friends": "Amigos"
	}
}